#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / 'src-tauri' / 'resources' / 'recipes' / 'catalog.json'
FIRMWARE_ROOT = ROOT / 'src-tauri' / 'resources' / 'firmware'
HEADER_NAME = 'BetterBoardBuildProvenance.h'
STAMPED_SOURCE_NAME = 'betterboard_stamped_source.ino'


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open('rb') as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b''):
            h.update(chunk)
    return h.hexdigest()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode('utf-8')).hexdigest()


def run(cmd: list[str]) -> str:
    proc = subprocess.run(cmd, text=True, capture_output=True)
    if proc.returncode != 0:
        raise RuntimeError((proc.stdout + '\n' + proc.stderr).strip())
    return (proc.stdout or proc.stderr).strip()


def recipe_by_id(recipe_id: str) -> dict:
    catalog = json.loads(CATALOG.read_text())
    for recipe in catalog:
        if recipe.get('id') == recipe_id:
            return recipe
    raise SystemExit(f'Unknown recipe: {recipe_id}')


def core_from_fqbn(fqbn: str) -> str:
    parts = fqbn.split(':')
    return ':'.join(parts[:2]) if len(parts) >= 2 else fqbn


def core_version(cli: str, core: str) -> str | None:
    try:
        raw = run([cli, 'core', 'list', '--format', 'json'])
        data = json.loads(raw)
        rows = data if isinstance(data, list) else data.get('platforms', data.get('installed_platforms', []))
        for row in rows or []:
            ident = row.get('id') or row.get('ID') or row.get('platform')
            if ident == core:
                return str(row.get('installed') or row.get('version') or row.get('latest') or '') or None
    except Exception:
        pass
    try:
        text = run([cli, 'core', 'list'])
        for line in text.splitlines():
            if core in line:
                fields = line.split()
                if len(fields) >= 2:
                    return fields[1]
    except Exception:
        pass
    return None


def build_identity_payload(*, recipe_id: str, fqbn: str, core: str, core_ver: str | None, cli_version: str, source_sha256: str) -> dict:
    return {
        'recipe_id': recipe_id,
        'fqbn': fqbn,
        'core': core,
        'core_version': core_ver,
        'arduino_cli_version': cli_version,
        'source_sha256': source_sha256,
    }


def build_id_for(payload: dict) -> tuple[str, str]:
    canonical = json.dumps(payload, sort_keys=True, separators=(',', ':'), ensure_ascii=True)
    full = sha256_text(canonical)
    return f'bb-{full[:20]}', full


def header_text(build_id: str, source_sha256: str, identity_sha256: str) -> str:
    return (
        '#pragma once\n'
        '// Generated by BetterBoard build provenance tooling.\n'
        f'#define BETTERBOARD_BUILD_ID "{build_id}"\n'
        f'#define BETTERBOARD_SOURCE_SHA256 "{source_sha256}"\n'
        f'#define BETTERBOARD_BUILD_IDENTITY_SHA256 "{identity_sha256}"\n'
    )


def stamp_firmware_source(source_text: str) -> str:
    include_anchor = '#include <Arduino.h>\n'
    if include_anchor not in source_text:
        raise RuntimeError('Firmware source has no #include <Arduino.h> anchor for build provenance stamping.')
    stamped = source_text.replace(
        include_anchor,
        include_anchor + f'#include "{HEADER_NAME}"\n',
        1,
    )
    info_anchor = '  Serial.println(F("#INFO_BEGIN"));\n'
    if info_anchor not in stamped:
        raise RuntimeError('Firmware source has no standard #INFO_BEGIN line; cannot inject device build identity safely.')
    info_stamp = (
        info_anchor
        + '  Serial.print(F("#BUILD_ID,")); Serial.println(BETTERBOARD_BUILD_ID);\n'
        + '  Serial.print(F("#SOURCE_SHA256,")); Serial.println(BETTERBOARD_SOURCE_SHA256);\n'
        + '  Serial.print(F("#BUILD_IDENTITY_SHA256,")); Serial.println(BETTERBOARD_BUILD_IDENTITY_SHA256);\n'
    )
    return stamped.replace(info_anchor, info_stamp, 1)


def main() -> int:
    ap = argparse.ArgumentParser(description='Compile one BetterBoard recipe and emit a reproducible build-provenance manifest.')
    ap.add_argument('--recipe', required=True, help='BetterBoard recipe id')
    ap.add_argument('--fqbn', required=True, help='Exact Arduino FQBN')
    ap.add_argument('--arduino-cli', default=shutil.which('arduino-cli') or 'arduino-cli')
    ap.add_argument('--out-dir', type=Path, required=True)
    args = ap.parse_args()

    recipe = recipe_by_id(args.recipe)
    sketch_name = recipe['sketch_name']
    source = FIRMWARE_ROOT / sketch_name / f'{sketch_name}.ino'
    if not source.is_file():
        raise SystemExit(f'Firmware source missing: {source}')

    args.out_dir.mkdir(parents=True, exist_ok=True)
    build_dir = args.out_dir / 'build'
    if build_dir.exists():
        shutil.rmtree(build_dir)
    build_dir.mkdir(parents=True)

    cli_version = run([args.arduino_cli, 'version'])
    core = core_from_fqbn(args.fqbn)
    core_ver = core_version(args.arduino_cli, core)
    source_sha = sha256_file(source)
    identity_payload = build_identity_payload(
        recipe_id=recipe['id'],
        fqbn=args.fqbn,
        core=core,
        core_ver=core_ver,
        cli_version=cli_version,
        source_sha256=source_sha,
    )
    build_id, identity_sha = build_id_for(identity_payload)
    provenance_header = header_text(build_id, source_sha, identity_sha)
    archived_header = args.out_dir / HEADER_NAME
    archived_header.write_text(provenance_header)

    original_source_text = source.read_text()
    stamped_source_text = stamp_firmware_source(original_source_text)
    stamped_source_sha = sha256_text(stamped_source_text)
    archived_stamped_source = args.out_dir / STAMPED_SOURCE_NAME
    archived_stamped_source.write_text(stamped_source_text)

    with tempfile.TemporaryDirectory(prefix='betterboard-build-') as tmp:
        sketch_dir = Path(tmp) / sketch_name
        sketch_dir.mkdir()
        sketch_copy = sketch_dir / source.name
        sketch_copy.write_text(stamped_source_text)
        (sketch_dir / HEADER_NAME).write_text(provenance_header)

        compile_cmd = [
            args.arduino_cli,
            'compile',
            '--fqbn', args.fqbn,
            '--build-path', str(build_dir),
            str(sketch_dir),
        ]
        compile_output = run(compile_cmd)

    artifacts = []
    for path in sorted(p for p in build_dir.rglob('*') if p.is_file()):
        if path.suffix.lower() not in {'.bin', '.elf', '.hex', '.map'}:
            continue
        artifacts.append({
            'path': str(path.relative_to(args.out_dir)),
            'bytes': path.stat().st_size,
            'sha256': sha256_file(path),
        })

    if not artifacts:
        raise RuntimeError('Compile succeeded but no .bin/.elf/.hex/.map build artifacts were found.')

    manifest = {
        'schema': 'betterboard.firmware-build/2',
        'created_at_utc': datetime.now(timezone.utc).isoformat(),
        'producer': 'scripts/esp32_build_manifest.py',
        'build_identity': {
            'build_id': build_id,
            'identity_sha256': identity_sha,
            'derivation': 'sha256(canonical recipe/fqbn/core-version/arduino-cli-version/source-sha256), build_id uses first 20 hex chars',
            'payload': identity_payload,
            'generated_header': HEADER_NAME,
            'device_info_contract': ['BUILD_ID', 'SOURCE_SHA256', 'BUILD_IDENTITY_SHA256'],
        },
        'recipe': {
            'id': recipe['id'],
            'title': recipe['title'],
            'sketch_name': sketch_name,
        },
        'target': {
            'fqbn': args.fqbn,
            'core': core,
            'core_version': core_ver,
        },
        'toolchain': {
            'arduino_cli': args.arduino_cli,
            'arduino_cli_version': cli_version,
            'compile_command': compile_cmd,
        },
        'source': {
            'repository_path': str(source.relative_to(ROOT)),
            'sha256': source_sha,
            'bytes': source.stat().st_size,
            'stamped_source_path': STAMPED_SOURCE_NAME,
            'stamped_source_sha256': stamped_source_sha,
            'stamping': 'temporary compile copy injects BetterBoardBuildProvenance.h and INFO build-identity fields; repository source remains unchanged',
        },
        'artifacts': artifacts,
        'compile_output': compile_output,
        'attestation_boundary': (
            'Build ID and artifact hashes identify this local compile output. When firmware built by this tool reports the same BUILD_ID '
            'through INFO, BetterBoard can associate the running firmware self-report with this manifest. This remains weaker than '
            'cryptographic device attestation or an independently read flash digest.'
        ),
    }

    manifest_path = args.out_dir / 'firmware_build_manifest.json'
    manifest_path.write_text(json.dumps(manifest, indent=2) + '\n')
    print(manifest_path)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
